# Generated by Django 4.2.4 on 2024-01-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
