# Generated by Django 4.2.4 on 2024-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("articles", "0005_userprofile"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_set", to="auth.permission"
            ),
        ),
    ]
