# Generated by Django 4.2.4 on 2024-01-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0006_alter_customuser_managers_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="user",),
        migrations.DeleteModel(name="CustomUser",),
        migrations.DeleteModel(name="UserProfile",),
    ]
