# Generated by Django 4.2.4 on 2024-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_article_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date of the publication"
            ),
        ),
    ]
