# Generated by Django 4.2.4 on 2024-02-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_userprofile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
